# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-26 16:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0002_auto_20191026_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snap',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
