# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-27 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0006_auto_20191027_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snap',
            name='content',
        ),
        migrations.RemoveField(
            model_name='snap',
            name='design',
        ),
        migrations.RemoveField(
            model_name='snap',
            name='link',
        ),
        migrations.RemoveField(
            model_name='snap',
            name='usability',
        ),
    ]
