# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0010_auto_20191031_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='snap',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
