# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-31 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0011_snap_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snap',
            old_name='snap',
            new_name='image',
        ),
    ]
